name: otp_poc_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_authenticator: ^1.4.0
  flutter_dotenv: ^5.1.0
  go_router: ^7.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
